### ISSUE TITLE
it doesnt work

### ISSUE THREAD

**Issue by ultraHatyy** [syyePhenomenol/HollowKnight.VanillaMapMod#2]
i tried all the hotkeys, it just doesnt work

**Comment by syyePhenomenol** [comment]
Hi, I'm going to need more details to diagnose this.

Which hotkeys in particular? VanillaMapMod only has Ctrl-M and Ctrl-T, and the latter only works when the mod is enabled.

Please provide other information such as a ModLog if you can.
