### ISSUE TITLE
Use randomizer logic?

### ISSUE THREAD

**Issue by thecnoNSMB** [syyePhenomenol/HollowKnight.VanillaMapMod#6]
I'm using this mod for my first playthrough of the game and it bugs (heh) me a little that many pins are shown despite me not being able to collect most of them yet. Would it be feasible to adapt the randomizer's logic to hide pins that are unable to be collected?

**Comment by syyePhenomenol** [comment]
Hi, this does seem like a feasible idea, but I haven't been actively working on the mod recently.

If I come back to development, I will find a way to incorporate your suggestion.

**Comment by syyePhenomenol** [comment]
By the way, locations not in logic are already represented by smaller and grayed out pins.

**Comment by thecnoNSMB** [comment]
> EDIT 2: In the case that you are asking for VanillaMapMod specifically to have rando logic, I don't think that this would be used by the large majority of people playing the game for the first time.

Yes, that's what I was asking. Perfectly understandable, thanks!
