### ISSUE TITLE
Vanilla pins not appearing and certain mod pins not dissapearing when collected

### ISSUE THREAD

**Issue by DreamerCodes** [syyePhenomenol/HollowKnight.VanillaMapMod#7]
Basically the title.

-All vanilla pins don't appear
-Vessel Fragments, Mask Shards, some Rancid Eggs, some Charms, some Shops, and Geo Rocks pins don't disappear when collected
-I added the mod before I created my saves
-If I switch the mode from normal to full, all vanilla pins appear [doesn't fix mod pins]

File stuff that might help
[FILE_STUFF.zip](https://github.com/user-attachments/files/16698387/FILE_STUFF.zip)

Thanks,
-Dreamer

**Comment by syyePhenomenol** [comment]
Please install and use RandoMapMod for a randomizer run instead.

If you have both VanillaMapMod and RandoMapMod installed, you can toggle through all the combined modes from the pause menu by clicking the "Mode" button.
